AppBundle\Entity\GalleryKsc:
    type: entity
    table: gallery_ksc
    indexes:
        FK1Group:
            columns:
                - group
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        initial:
            type: string
            nullable: false
            length: 50
            fixed: false
            default: '0'
        gallery:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        status:
            type: string
            nullable: false
            length: 2
            fixed: false
            default: '1'
    manyToOne:
        group:
            targetEntity: GroupsKsc
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                group:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
