AppBundle\Entity\GroupsKsc:
    type: entity
    table: groups_ksc
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
        initial:
            type: string
            nullable: true
            length: 10
            fixed: false
        description:
            type: string
            nullable: true
            length: 255
            fixed: false
            default: '"Description"'
        status:
            type: string
            nullable: false
            length: 2
            fixed: false
            default: '1'
    lifecycleCallbacks: {  }
