AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
        surname:
            type: string
            nullable: true
            length: 255
            fixed: false
        role:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '0'
        state:
            type: string
            nullable: false
            length: 255
            fixed: false
            default: '1'
    lifecycleCallbacks: {  }
